# Generated by Django 2.2.3 on 2019-07-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False, verbose_name='email')),
                ('data_de_nascimento', models.DateField(verbose_name='data_de_nascimento')),
                ('atualizado_por_ultimo_em', models.DateField(auto_now_add=True, verbose_name='atualizado_por_ultimo')),
                ('permissao', models.IntegerField(default=0, verbose_name='permissao')),
                ('is_professor', models.BooleanField(default=False, verbose_name='is_professor')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
    ]
