# Generated by Django 2.2.3 on 2019-07-31 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('area_de_conhecimento', models.CharField(max_length=50)),
                ('id_usuario_responsavel', models.IntegerField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuarios', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'materia',
                'verbose_name_plural': 'materias',
            },
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('tags', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.TimeField(auto_now=True)),
                ('fk_materia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Materia')),
                ('fk_usuario_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'publicacao',
                'verbose_name_plural': 'publicacoes',
            },
        ),
        migrations.CreateModel(
            name='PlanoDeEstudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_administrador', to=settings.AUTH_USER_MODEL)),
                ('publicacoes', models.ManyToManyField(to='nucleo.Publicacao')),
                ('seguidores', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'plano_de_estudo',
            },
        ),
    ]
