# Generated by Django 2.2.3 on 2019-07-31 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planodeestudo',
            options={'verbose_name': 'plano_de_estudo', 'verbose_name_plural': 'planos_de_estudo'},
        ),
    ]
