# Generated by Django 2.2.3 on 2019-07-31 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nucleo', '0002_auto_20190731_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacao',
            old_name='fk_materia_id',
            new_name='materia_id',
        ),
        migrations.RenameField(
            model_name='publicacao',
            old_name='fk_usuario_email',
            new_name='usuario_email',
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.CharField(max_length=255)),
                ('horario', models.DateTimeField()),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_publicacao', to='nucleo.Publicacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historico',
                'verbose_name_plural': 'historicos',
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('is_resolvido', models.BooleanField(default=False)),
                ('respondido_em', models.DateTimeField(auto_now=True)),
                ('aberto_em', models.DateTimeField(auto_now_add=True)),
                ('mensagem', models.CharField(max_length=255)),
                ('aberto_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aberto_por', to=settings.AUTH_USER_MODEL)),
                ('resolvido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolvido_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'chamado',
                'verbose_name_plural': 'chamados',
            },
        ),
    ]
