# Generated by Django 2.2.3 on 2019-07-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_auto_20190731_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planodeestudo',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
